# Generated by Django 3.2.9 on 2021-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
