# Generated by Django 3.2.9 on 2021-12-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='name',
        ),
    ]
