# Generated by Django 3.2.9 on 2021-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=4, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
